### ISSUE TITLE
请问如何让保存文件时添加后缀

### ISSUE THREAD

**Issue by 2584191127** [fym202/DataAugYolo#3]
我将
```
# random_bright
t_img, t_boxes = DAD.random_bright(img.clone()), boxes
save_Yolo(to_image(t_img), boxes, save_path, prefix="rb_", image_name=image_name)
```
改成了
```
# random_bright
t_img, t_boxes = DAD.random_bright(img.clone()), boxes
save_Yolo(to_image(t_img), boxes, save_path, suffix="_rb, image_name=image_name)
```
在save_YOLO函数里也改了
把
```
img.save(os.path.join(save_path, "images", prefix + image_name))
with open(os.path.join(save_path, "labels", prefix + image_name[0:len(image_name)-4] + ".txt"), 'w', encoding="utf-8") as f:
```
改成
```
img.save(os.path.join(save_path, "images", image_name + suffix))
with open(os.path.join(save_path, "labels", image_name[0:len(image_name)-4] + suffix + ".txt"), 'w', encoding="utf-8") as f:
```
但是运行的时候报错了
```
dealing: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
ERROR: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg is bad.
end: fbd02b4f1eac089a9af1a9e0a24e888e3226d6bc.jpg
```

**Comment by fym202** [comment]
因为图片名image_name一般是 xxx.jpg, 如果再后面直接加后缀，就变成xxx.jpgsuffix了，图片就会格式出错。把save_YOLO中的img.save一行改成如下
`img.save(os.path.join(save_path, "images", image_name[0:len(image_name)-4] + suffix + image_name[len(image_name)-4:]))`

**Comment by 2584191127** [comment]
原来是这样，问题解决了，谢谢大佬

**Comment by 2584191127** [comment]
请问这个问题怎么解决，我换了一个数据集就报错了
```
Traceback (most recent call last):
  File "D:\Desktop\yolov8-data-processor-master\DataAugOnDetection.py", line 337, in <module>
    runAugumentation(image_path, label_path, save_path)
  File "D:\Desktop\yolov8-data-processor-master\DataAugOnDetection.py", line 282, in runAugumentation
    boxes = torch.tensor(boxes)
ValueError: expected sequence of length 255 at dim 1 (got 147)
```
图片和标注如下
![110](https://github.com/fym202/DataAugYolo/assets/78305714/50dc538b-cfb9-483e-ae5a-18712396484e)
```
0 0.816794 0.304659 0.812977 0.304659 0.80916 0.301075 0.801527 0.301075 0.78626 0.286738 0.778626 0.286738 0.774809 0.290323 0.770992 0.290323 0.763359 0.297491 0.759542 0.297491 0.751908 0.304659 0.748092 0.304659 0.740458 0.311828 0.736641 0.311828 0.729008 0.318996 0.725191 0.318996 0.717557 0.326165 0.71374 0.326165 0.706107 0.333333 0.70229 0.333333 0.694656 0.340502 0.69084 0.340502 0.683206 0.34767 0.679389 0.34767 0.675573 0.351254 0.671756 0.351254 0.664122 0.358423 0.660305 0.358423 0.652672 0.365591 0.648855 0.365591 0.641221 0.37276 0.637405 0.37276 0.629771 0.379928 0.625954 0.379928 0.618321 0.387097 0.614504 0.387097 0.60687 0.394265 0.603053 0.394265 0.59542 0.401434 0.591603 0.401434 0.583969 0.408602 0.580153 0.408602 0.576336 0.412186 0.572519 0.412186 0.564885 0.419355 0.561069 0.419355 0.553435 0.426523 0.549618 0.426523 0.541985 0.433692 0.538168 0.433692 0.530534 0.44086 0.526718 0.44086 0.519084 0.448029 0.515267 0.448029 0.507634 0.455197 0.503817 0.455197 0.496183 0.462366 0.492366 0.462366 0.484733 0.469534 0.480916 0.469534 0.473282 0.476703 0.469466 0.476703 0.469466 0.483871 0.473282 0.487455 0.473282 0.491039 0.484733 0.501792 0.484733 0.505376 0.48855 0.508961 0.496183 0.508961 0.5 0.505376 0.503817 0.505376 0.51145 0.498208 0.515267 0.498208 0.522901 0.491039 0.526718 0.491039 0.534351 0.483871 0.538168 0.483871 0.545802 0.476703 0.549618 0.476703 0.557252 0.469534 0.561069 0.469534 0.568702 0.462366 0.572519 0.462366 0.580153 0.455197 0.583969 0.455197 0.591603 0.448029 0.59542 0.448029 0.603053 0.44086 0.60687 0.44086 0.610687 0.437276 0.614504 0.437276 0.622137 0.430108 0.625954 0.430108 0.633588 0.422939 0.637405 0.422939 0.645038 0.415771 0.648855 0.415771 0.656489 0.408602 0.660305 0.408602 0.667939 0.401434 0.671756 0.401434 0.679389 0.394265 0.683206 0.394265 0.69084 0.387097 0.694656 0.387097 0.70229 0.379928 0.706107 0.379928 0.709924 0.376344 0.71374 0.376344 0.721374 0.369176 0.725191 0.369176 0.732824 0.362007 0.736641 0.362007 0.744275 0.354839 0.748092 0.354839 0.755725 0.34767 0.759542 0.34767 0.767176 0.340502 0.770992 0.340502 0.778626 0.333333 0.782443 0.333333 0.790076 0.326165 0.793893 0.326165 0.801527 0.318996 0.805344 0.318996 0.812977 0.311828 0.816794 0.311828
1 0.133588 0.297491 0.129771 0.301075 0.129771 0.304659 0.125954 0.308244 0.125954 0.311828 0.122137 0.315412 0.122137 0.318996 0.118321 0.322581 0.118321 0.329749 0.122137 0.329749 0.125954 0.333333 0.129771 0.333333 0.137405 0.340502 0.137405 0.34767 0.133588 0.351254 0.118321 0.351254 0.114504 0.34767 0.103053 0.34767 0.103053 0.351254 0.0992366 0.354839 0.0992366 0.362007 0.0954198 0.365591 0.0954198 0.376344 0.0916031 0.379928 0.0954198 0.383513 0.0954198 0.387097 0.0992366 0.387097 0.103053 0.390681 0.110687 0.390681 0.114504 0.394265 0.125954 0.394265 0.129771 0.397849 0.141221 0.397849 0.141221 0.394265 0.145038 0.390681 0.145038 0.383513 0.148855 0.379928 0.148855 0.369176 0.152672 0.365591 0.148855 0.362007 0.148855 0.354839 0.152672 0.351254 0.164122 0.351254 0.171756 0.358423 0.175573 0.358423 0.179389 0.362007 0.183206 0.362007 0.187023 0.365591 0.194656 0.365591 0.198473 0.362007 0.198473 0.358423 0.20229 0.354839 0.20229 0.351254 0.206107 0.34767 0.206107 0.344086 0.209924 0.340502 0.209924 0.333333 0.206107 0.333333 0.20229 0.329749 0.198473 0.329749 0.19084 0.322581 0.187023 0.322581 0.183206 0.318996 0.179389 0.318996 0.175573 0.315412 0.171756 0.315412 0.167939 0.311828 0.164122 0.311828 0.156489 0.304659 0.152672 0.304659 0.148855 0.301075 0.145038 0.301075 0.141221 0.297491
1 0.0916031 0.408602 0.0916031 0.412186 0.0877863 0.415771 0.0877863 0.422939 0.0839695 0.426523 0.0839695 0.437276 0.0801527 0.44086 0.0839695 0.444444 0.0839695 0.448029 0.0877863 0.448029 0.0916031 0.451613 0.0916031 0.458781 0.0839695 0.46595 0.0801527 0.46595 0.0801527 0.469534 0.0763359 0.473118 0.0763359 0.498208 0.0801527 0.501792 0.0801527 0.505376 0.0839695 0.505376 0.0877863 0.508961 0.0877863 0.516129 0.0839695 0.519713 0.0763359 0.519713 0.0725191 0.523297 0.0687023 0.523297 0.0687023 0.526882 0.0648855 0.530466 0.0687023 0.53405 0.0687023 0.544803 0.0725191 0.548387 0.0725191 0.555556 0.0763359 0.55914 0.0763359 0.562724 0.0839695 0.562724 0.0877863 0.566308 0.0877863 0.573477 0.0801527 0.584229 0.0839695 0.587814 0.0839695 0.598566 0.0877863 0.602151 0.0877863 0.609319 0.0916031 0.612903 0.0916031 0.616487 0.10687 0.616487 0.110687 0.620072 0.110687 0.62724 0.10687 0.630824 0.103053 0.630824 0.0992366 0.634409 0.0954198 0.634409 0.0954198 0.641577 0.0992366 0.645161 0.0992366 0.648746 0.103053 0.65233 0.103053 0.655914 0.10687 0.659498 0.10687 0.663082 0.110687 0.666667 0.110687 0.670251 0.118321 0.670251 0.122137 0.666667 0.129771 0.666667 0.133588 0.670251 0.133588 0.677419 0.125954 0.684588 0.122137 0.684588 0.118321 0.688172 0.118321 0.695341 0.122137 0.698925 0.122137 0.702509 0.125954 0.706093 0.125954 0.709677 0.129771 0.713262 0.129771 0.716846 0.133588 0.72043 0.133588 0.724014 0.145038 0.734767 0.145038 0.738351 0.148855 0.741935 0.156489 0.741935 0.164122 0.734767 0.167939 0.734767 0.179389 0.724014 0.183206 0.724014 0.194656 0.713262 0.198473 0.713262 0.209924 0.702509 0.21374 0.702509 0.217557 0.698925 0.217557 0.691756 0.21374 0.688172 0.21374 0.684588 0.20229 0.673835 0.20229 0.670251 0.198473 0.666667 0.19084 0.666667 0.183206 0.673835 0.179389 0.673835 0.171756 0.681004 0.160305 0.681004 0.156489 0.677419 0.156489 0.673835 0.145038 0.666667 0.145038 0.655914 0.148855 0.65233 0.152672 0.65233 0.156489 0.648746 0.160305 0.648746 0.164122 0.645161 0.167939 0.645161 0.167939 0.637993 0.164122 0.634409 0.164122 0.630824 0.160305 0.62724 0.160305 0.623656 0.156489 0.620072 0.156489 0.616487 0.152672 0.612903 0.152672 0.609319 0.145038 0.609319 0.141221 0.612903 0.133588 0.612903 0.129771 0.609319 0.129771 0.602151 0.125954 0.598566 0.125954 0.587814 0.122137 0.584229 0.122137 0.577061 0.118321 0.573477 0.118321 0.562724 0.122137 0.55914 0.133588 0.55914 0.137405 0.555556 0.141221 0.555556 0.141221 0.551971 0.145038 0.548387 0.141221 0.544803 0.141221 0.53405 0.137405 0.530466 0.137405 0.523297 0.133588 0.519713 0.133588 0.516129 0.125954 0.516129 0.122137 0.512545 0.122137 0.501792 0.125954 0.498208 0.125954 0.473118 0.122137 0.469534 0.122137 0.458781 0.125954 0.455197 0.141221 0.455197 0.141221 0.451613 0.145038 0.448029 0.145038 0.44086 0.148855 0.437276 0.148855 0.426523 0.152672 0.422939 0.148855 0.419355 0.148855 0.415771 0.145038 0.415771 0.141221 0.412186 0.118321 0.412186 0.114504 0.408602
1 0.236641 0.179211 0.232824 0.193548 0.217557 0.197133 0.19084 0.222222 0.19084 0.236559 0.175573 0.240143 0.148855 0.265233 0.148855 0.272401 0.175573 0.297491 0.183206 0.297491 0.209924 0.272401 0.21374 0.258065 0.236641 0.265233 0.263359 0.240143 0.263359 0.225806 0.29771 0.197133 0.320611 0.204301 0.343511 0.189964 0.351145 0.164875 0.40458 0.157706 0.408397 0.164875 0.442748 0.16129 0.454198 0.150538 0.454198 0.132616 0.503817 0.136201 0.507634 0.172043 0.549618 0.179211 0.561069 0.143369 0.610687 0.146953 0.614504 0.168459 0.645038 0.179211 0.671756 0.175627 0.706107 0.189964 0.709924 0.204301 0.698473 0.222222 0.725191 0.243728 0.748092 0.236559 0.778626 0.265233 0.774809 0.286738 0.80916 0.318996 0.828244 0.354839 0.824427 0.365591 0.78626 0.376344 0.790076 0.401434 0.79771 0.415771 0.824427 0.408602 0.839695 0.412186 0.839695 0.462366 0.820611 0.476703 0.820611 0.501792 0.832061 0.512545 0.820611 0.55914 0.805344 0.562724 0.790076 0.591398 0.790076 0.598566 0.80916 0.605735 0.816794 0.620072 0.80916 0.623656 0.790076 0.663082 0.763359 0.655914 0.748092 0.673835 0.744275 0.688172 0.751908 0.702509 0.721374 0.741935 0.71374 0.741935 0.694656 0.72043 0.660305 0.738351 0.660305 0.74552 0.706107 0.802867 0.736641 0.78853 0.740458 0.777778 0.721374 0.756272 0.721374 0.749104 0.732824 0.74552 0.755725 0.763441 0.763359 0.763441 0.78626 0.738351 0.78626 0.727599 0.801527 0.724014 0.816794 0.706093 0.820611 0.691756 0.801527 0.677419 0.801527 0.670251 0.812977 0.666667 0.832061 0.673835 0.847328 0.645161 0.843511 0.62724 0.851145 0.623656 0.866412 0.594982 0.866412 0.587814 0.847328 0.580645 0.843511 0.569892 0.870229 0.566308 0.881679 0.53405 0.877863 0.526882 0.851145 0.519713 0.854962 0.508961 0.877863 0.508961 0.889313 0.498208 0.889313 0.473118 0.881679 0.462366 0.889313 0.444444 0.889313 0.419355 0.885496 0.412186 0.858779 0.408602 0.862595 0.397849 0.889313 0.390681 0.889313 0.376344 0.877863 0.351254 0.858779 0.34767 0.866412 0.326165 0.851145 0.297491 0.835878 0.293907 0.847328 0.268817 0.820611 0.243728 0.812977 0.243728 0.793893 0.218638 0.770992 0.200717 0.770992 0.193548 0.744275 0.172043 0.736641 0.172043 0.721374 0.189964 0.71374 0.189964 0.709924 0.179211 0.721374 0.154122 0.679389 0.139785 0.664122 0.125448 0.622137 0.11828 0.60687 0.103943 0.564885 0.103943 0.561069 0.0967742 0.534351 0.0896057 0.507634 0.09319 0.496183 0.0860215 0.469466 0.0860215 0.458015 0.0967742 0.454198 0.11828 0.442748 0.114695 0.438931 0.100358 0.351145 0.114695 0.339695 0.125448 0.339695 0.154122 0.332061 0.154122 0.320611 0.136201 0.28626 0.154122 0.293893 0.172043 0.290076 0.182796 0.282443 0.182796 0.267176 0.164875
```
[110.txt](https://github.com/fym202/DataAugYolo/files/14611562/110.txt)
